FROM eclipse-temurin:17-jdk AS build
wORKDIR /app
COPY . .
RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

fROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.war app.war
EXPOSE 8087
ENTRYPOINT ["java", "-jar", "app.war"]