dept.id=101
dept.name=IT
dept.loc=Mumbai

emp1.id=1
emp1.name=Rohit
emp1.salary=50000
emp1.mobile=9876543210
emp1.email=rohit@gmail.com

emp2.id=2
emp2.name=Aman
emp2.salary=60000
emp2.mobile=9876543211
emp2.email=aman@gmail.com

emp3.id=3
emp3.name=Neha
emp3.salary=70000
emp3.mobile=9876543212
emp3.email=neha@gmail.com